### ISSUE TITLE
[Masalah Koneksi]

### ISSUE THREAD

**Issue by ad3n** [heriant0/go-fiber#2]
Coba jalankan perintah `mysql -uroot -ppass123 db_course ` hasilnya nanti di-SS di sini ya mas

**Comment by heriant0** [comment]
<img width="721" alt="cc" src="https://user-images.githubusercontent.com/42226352/176345311-2504bf51-356f-4997-a287-9eaf713ccaba.png">

ini saya pke WSL, saya juga sudah install di windowsnya

**Comment by ad3n** [comment]
@heriant0 itu sepertinya mysqlnya ga belum jalan mas

**Comment by heriant0** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/42226352/176778767-cf702723-d85e-453c-91ff-41dd321a144a.png">

mysqlnya sudah jalan tapi masih belum bisa connect 
<img width="882" alt="image" src="https://user-images.githubusercontent.com/42226352/176779102-fd7a502c-e380-4ffc-bd8f-501651f1dec0.png">

**Comment by ad3n** [comment]
@heriant0 kalau misal `mysql -uroot db_course` tetap bisa masuk ga kalau pakai command line? kalau bisa berarti  kemungkinan masih pakai auth socket, ini masalah umum kalau install mysql via package manager

Solusinya, disabled plugin auth socket atau unix socket terus set password, atau kalau mau gampang, bisa pakai mysql docker mas

Untuk ujicoba, bikin koneksinya statis aja dulu, ga perlu via `.env` di-hardcode dulu aja, kalau sudah jalan, nanti baru dicoba pakai `.env`
